#!/bin/sh

mkdir -p proto/sbin
mkdir -p proto/etc/sv
mkdir -p proto/etc/sv/getty-1
mkdir -p proto/etc/sv/getty-2
mkdir -p proto/etc/sv/getty-3
mkdir -p proto/etc/sv/getty-4
mkdir -p proto/etc/runit
mkdir -p proto/service

cp command/* proto/sbin/
cp proto/sbin/runit proto/sbin/init

cp etc/freebsd/* proto/etc/runit/
cp -r etc/freebsd/getty-ttyv0/* proto/etc/sv/getty-1/
cp -r etc/freebsd/getty-ttyv1/* proto/etc/sv/getty-2/
cp -r etc/freebsd/getty-ttyv2/* proto/etc/sv/getty-3/
cp -r etc/freebsd/getty-ttyv3/* proto/etc/sv/getty-4/

ln -s /etc/sv/getty-1 proto/service/getty-1
ln -s /etc/sv/getty-2 proto/service/getty-2
ln -s /etc/sv/getty-3 proto/service/getty-3 
ln -s /etc/sv/getty-4 proto/service/getty-4

echo "### Generating package: ###"
pkgmk -o -b `pwd`/proto/ -f pkgproto -d .
