#!/bin/sh

mkdir -p proto/sbin
mkdir -p proto/usr/bin
mkdir -p proto/usr/sbin
mkdir -p proto/usr/share/man/man8

cpsvcbundle ()
{
	SVC=$1
	NEWSVC=$2
	LOG=$3

	mkdir -p proto/etc/sv/$NEWSVC
	[ "$LOG" == "yes" ] && mkdir -p proto/etc/sv/$NEWSVC/log

	cp -r etc/freebsd/$SVC/* proto/etc/sv/$NEWSVC/
}

cpsvcbundle amd amd yes
cpsvcbundle casperd casperd no
cpsvcbundle cron cron yes
cpsvcbundle dbus dbus yes
cpsvcbundle getty-ttyv0 getty-1 no
cpsvcbundle getty-ttyv1 getty-2 no
cpsvcbundle getty-ttyv2 getty-3 no
cpsvcbundle getty-ttyv3 getty-4 no
cpsvcbundle hald hald yes
cpsvcbundle rpc.statd rpc.statd yes
cpsvcbundle rpc.lockd rpc.lockd yes
cpsvcbundle rpcbind rpcbind yes
cpsvcbundle sm.submit sm.submit no
cpsvcbundle sm.mspqueue sm.mspqueue no
cpsvcbundle ntpd ntpd no
cpsvcbundle powerd powerd yes
cpsvcbundle sshd sshd no

mkdir -p proto/etc/runit
mkdir -p proto/service

cp man/* proto/usr/share/man/man8/

cp command/* proto/sbin/
mv proto/sbin/svcs proto/usr/bin/svcs
mv proto/sbin/svcctl proto/usr/sbin/svcctl
cp proto/sbin/runit-init proto/sbin/telinit

cp etc/freebsd/* proto/etc/runit/


echo "### Generating package: ###"
/usr/5bin/pkgmk -o -b `pwd`/proto/ -f pkgproto -d .
