#!/bin/sh

mkdir -p proto/sbin
mkdir -p proto/usr/bin
mkdir -p proto/usr/sbin
mkdir -p proto/usr/share/man/man8
mkdir -p proto/etc/sv
mkdir -p proto/etc/sv/amd
mkdir -p proto/etc/sv/amd/log
mkdir -p proto/etc/sv/cron
mkdir -p proto/etc/sv/cron/log
mkdir -p proto/etc/sv/getty-1
mkdir -p proto/etc/sv/getty-2
mkdir -p proto/etc/sv/getty-3
mkdir -p proto/etc/sv/getty-4
mkdir -p proto/etc/sv/rpc.statd/log
mkdir -p proto/etc/sv/rpc.lockd/log
mkdir -p proto/etc/sv/rpcbind/log
mkdir -p proto/etc/sv/ntpd
mkdir -p proto/etc/sv/sshd
mkdir -p proto/etc/runit
mkdir -p proto/service

cp man/* proto/usr/share/man/man8/

cp command/* proto/sbin/
mv proto/sbin/svcs proto/usr/bin/svcs
mv proto/sbin/svcctl proto/usr/sbin/svcctl
cp proto/sbin/runit-init proto/sbin/init

cp etc/freebsd/* proto/etc/runit/
cp -r etc/freebsd/amd/* proto/etc/sv/amd/
cp -r etc/freebsd/cron/* proto/etc/sv/cron/
cp -r etc/freebsd/getty-ttyv0/* proto/etc/sv/getty-1/
cp -r etc/freebsd/getty-ttyv1/* proto/etc/sv/getty-2/
cp -r etc/freebsd/getty-ttyv2/* proto/etc/sv/getty-3/
cp -r etc/freebsd/getty-ttyv3/* proto/etc/sv/getty-4/
cp -r etc/freebsd/rpcbind/* proto/etc/sv/rpcbind/
cp -r etc/freebsd/rpc.statd/* proto/etc/sv/rpc.statd/
cp -r etc/freebsd/rpc.lockd/* proto/etc/sv/rpc.lockd/
cp -r etc/freebsd/ntpd/* proto/etc/sv/ntpd/
cp -r etc/freebsd/sshd/* proto/etc/sv/sshd/


echo "### Generating package: ###"
/usr/5bin/pkgmk -o -b `pwd`/proto/ -f pkgproto -d .
