#!/bin/sh

CHROOTDIR="${BASEDIR}"

disable_in_rc_conf()
{
	name=$1
	cmdname=$2
	
	disable="${name}_enable=\"NO\""

	echo "checking if $name enabled in /etc/rc.conf..."
	if grep "$disable" ${BASEDIR}/etc/rc.conf; then
		echo "$name disabled in /etc/rc.conf"
	else
		echo "stopping $name service..."
		${BASEDIR}/etc/rc.d/$cmdname stop
		echo "disabling $name in /etc/rc.conf..."
		echo $disable >> ${BASEDIR}/etc/rc.conf
	fi
}

set_loaderconf_init_path()
{	
	initpath="init_path=\"/sbin/runit:/sbin/oinit:/sbin/init.bak:/rescue/init\""

	echo "checking if init_path set properly in /boot/loader.conf..."
	if grep "$initpath" ${BASEDIR}/boot/loader.conf; then
		echo "init_path is already properly set in /etc/rc.conf"
	else
		echo "setting init_path in /boot/loader.conf..."
		echo $initpath >> ${BASEDIR}/boot/loader.conf
	fi
}

if [ -f ${BASEDIR}/etc/rc.conf ]; then
	disable_in_rc_conf cron cron
	disable_in_rc_conf amd amd
	disable_in_rc_conf rpcbind rpcbind
	disable_in_rc_conf rpc_statd statd
	disable_in_rc_conf rpc_lockd lockd
	disable_in_rc_conf nfs_client nfsclient
	disable_in_rc_conf ntpd ntpd
	disable_in_rc_conf sshd sshd
fi

if [ -f ${BASEDIR}/boot/loader.conf ]; then
	set_loaderconf_init_path
fi

exit 0
