#!/bin/sh
# system one time tasks part 1

PATH=/sbin:/bin:/usr/sbin:/usr/bin
trap : 2
trap : 3

mount -t tmpfs -o rw -o mode=777 tmpfs /tmp
mount -t procfs proc /proc
mount -uw /
zfs mount -a
mkdir -p /run
mount -t tmpfs -o rw -o mode=777 tmpfs /run
rm -rf /var/run
ln -s /var/run /run
mkdir -p /run/svc/sysinit

rm -rf /service/wpa_supplicant* /service/dhclient*

sh -p
