#!/bin/sh

/sbin/sv start rpc.statd >/dev/null|| exit 1

sleep 0.5 #give rpc.statd a chance to get started properly

if [ -f ./svc.conf ]; then
	. ./svc.conf
fi

exec 2>&1
# the -d option provides logs, -n disables fork
exec /usr/sbin/rpc.lockd -n -d 1 $flags

