# $Sunshine$

LIB=time
SRCS=iopause.c	tai_sub.c	taia_approx.c	taia_now.c	taia_uint.c \
		tai_now.c	tai_unpack.c	taia_frac.c	taia_pack.c \
		tai_pack.c	taia_add.c	taia_less.c	taia_sub.c fmt_ptime.c

clean: libclean

install:

.include <../runit.prog.mk>
.include <bsd.lib.mk>
