# $Sunshine$

LIB=byte
SRCS=byte_chr.c	byte_diff.c	fmt_uint0.c	str_chr.c	str_start.c \
		byte_copy.c	byte_rchr.c	fmt_ulong.c	str_diff.c \
		byte_cr.c	fmt_uint.c	scan_ulong.c	str_len.c

clean: libclean

install:

.include <../runit.prog.mk>
.include <bsd.lib.mk>
