# $Sunshine$

PROG=runsv
SRCS=runsv.c 
MAN=runsv.8

BINDIR= /sbin

DPADD= ${LIBTIME} ${LIBUNIX} ${LIBBYTE} 
LDADD= ${LIBTIME} ${LIBUNIX} ${LIBBYTE}

.include <../runit.prog.mk>
.include <bsd.prog.mk>
