# $Sunshine$

PROG=telinit
SRCS=telinit.c 
MAN=telinit.8

BINDIR= /sbin

DPADD= ${LIBTIME} ${LIBUNIX} ${LIBBYTE} 
LDADD= ${LIBTIME} ${LIBUNIX} ${LIBBYTE}

.include <../runit.prog.mk>
.include <bsd.prog.mk>
