#!/bin/sh

set -e
CHOWN=/usr/sbin/chown
CHPST=/libexec/svc/chpst
SVLOGD=/libexec/svc/svlogd

if [ $0 != "./run" ];then
echo "This script meant to be linked as ./run in a service/log directory only!"
	exit 1
fi

curdir=$(basename $(pwd))

if [ "$curdir" != "log" ];then
echo "This script meant to be run from a service/log directory only!"
	exit 1
fi

if [ -f ./conf ];then
source ./conf
fi

#if [ ! -v SV_TIMESTAMP ];then # missing -v operator in /bin/sh
	#echo "Setting default timestamp"
	# Default to readable timestamps
	SV_TIMESTAMP="-tt"
#fi

if [ "x$SV_LOGDIR" != "x" ];then
logdir=$SV_LOGDIR
fi

if [ -w /var/log ];then
	user_group=${USERGROUP:-daemon:wheel}

	if [ "x$logdir" == "x" ];then
		logdir=$(basename $(dirname $(pwd)))
	fi

	[ -d "/var/svc/log/$logdir" ] || mkdir -p "/var/svc/log/$logdir"
	$CHOWN daemon:wheel /var/svc/log/$logdir
	[ -L ./main ] || [ -d ./main ] || ln -s "/var/svc/log/$logdir" ./main
	[ -L ./current ] || ln -s main/current

	if [ "x$CURRENT_LOG_FILE" != "x" ];then
		[ -L "/var/svc/log/$logdir/$CURRENT_LOG_FILE" ] || ln -s current "/var/svc/log/$logdir/$CURRENT_LOG_FILE"
	fi

	usergroup="daemon:wheel"
	if [ "$usergroup" != "$user_group" ];then
		$CHOWN -R $user_group "/var/svc/log/$logdir"
	fi

	#echo Logging as $user_group to /var/svc/log/$logdir
	#cd /var/svc/log/$logdir
	exec $CHPST -u $user_group $SVLOGD ${SV_TIMESTAMP} ./main
else
	echo Logging in $PWD
	if [ "x$CURRENT_LOG_FILE" != "x" ];then
		[ -L "$CURRENT_LOG_FILE" ] || ln -s current "$CURRENT_LOG_FILE"
	fi
	exec $SVLOGD ${SV_TIMESTAMP} ./
fi
