# $Sunshine$

PROG=runit
SRCS=runit.c 
MAN=runit.8

BINDIR= /sbin

DPADD= ${LIBTIME} ${LIBUNIX} ${LIBBYTE} 
LDADD= ${LIBTIME} ${LIBUNIX} ${LIBBYTE}

.include <../runit.prog.mk>
.include <bsd.prog.mk>
