# $Sunshine$

PROG=runsvdir
SRCS=runsvdir.c 
MAN=runsvdir.8

BINDIR= /sbin

DPADD= ${LIBTIME} ${LIBUNIX} ${LIBBYTE} 
LDADD= ${LIBTIME} ${LIBUNIX} ${LIBBYTE}

.include <../runit.prog.mk>
.include <bsd.prog.mk>
