.PHONY: clean All

All:
	@echo "----------Building project:[ svc_restartd - Debug ]----------"
	@$(MAKE) -f  "svc_restartd.mk"
clean:
	@echo "----------Cleaning project:[ svc_restartd - Debug ]----------"
	@$(MAKE) -f  "svc_restartd.mk" clean
