# $Sunshine$

LIB=unix
SRCS=alloc.c		coe.c		ndelay_on.c	seek_set.c	stralloc_opyb.c \
		alloc_re.c	env.c		open_append.c	sgetopt.c	stralloc_opys.c \
		buffer.c	error.c		open_read.c	sig.c		stralloc_pend.c \
		buffer_0.c	error_str.c	open_trunc.c	sig_block.c	strerr_die.c \
		buffer_1.c	fd_copy.c	open_write.c	sig_catch.c	strerr_sys.c \
		buffer_2.c	fd_move.c	openreadclose.c	sig_pause.c	subgetopt.c \
		buffer_get.c	fifo.c		pathexec_env.c	stralloc_cat.c	wait_nohang.c \
		buffer_put.c	lock_ex.c	pathexec_run.c	stralloc_catb.c	wait_pid.c \
		buffer_read.c	lock_exnb.c	prot.c		stralloc_cats.c \
		buffer_write.c	ndelay_off.c	readclose.c	stralloc_eady.c uidgid.c

clean: libclean

install:

.include <../runit.prog.mk>
.include <bsd.lib.mk>
