#!/bin/sh

. ./svc.conf
. ./netif.subr
. /etc/defaults/rc.conf
. /etc/rc.conf
. /etc/network.subr

sv start sysctl

doclear()
{
	_clone_down=
	network_stop0 $*
}

vnet_up()
{
	cmdifn=$*

	network_common ifn_vnetup $cmdifn
}

vnet_down()
{
	cmdifn=$*

	network_common ifn_vnetdown $cmdifn
}

_if=

# Set the list of interfaces to work on.
#
cmdifn=$*

if [ -z "$cmdifn" ]; then
	#
	# We're operating as a general network start routine.
	#

	# disable SIGINT (Ctrl-c) when running at startup
	trap : 2
fi

# Create cloned interfaces
clone_up $cmdifn

# Rename interfaces.
ifnet_rename $cmdifn

# Configure the interface(s).
network_common ifn_start $cmdifn

if [ -f /etc/rc.d/ipfilter ] ; then
	# Resync ipfilter
	/etc/rc.d/ipfilter quietresync
fi
if [ -f /etc/rc.d/bridge -a -n "$cmdifn" ] ; then
	/etc/rc.d/bridge start $cmdifn
fi
if [ -f /etc/rc.d/routing -a -n "$cmdifn" ] ; then
	for _if in $cmdifn; do
		/etc/rc.d/routing start any $_if
	done
fi
