#!/bin/sh

/sbin/sv start rpcbind || exit 1

sleep 0.5 # give rpcbind a chance to start properly

if [ -f ./svc.conf ]; then
	. ./svc.conf
fi

exec 2>&1
# the -d option provides logs, -n disables fork
exec /usr/sbin/rpc.statd -n -d $flags

