# $Sunshine$

SUBDIR=libbyte \
		libtime \
		libunix \
		runsv \
		runsvdir \
		pid1 \
		sv \
		telinit \
		svlogd \
		chpst \
		runsvchdir \
		utils

	
preinstall:
	mkdir -p ${DESTDIR}/usr/share/man/man8

.include <bsd.subdir.mk>
